spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  data:
    redis:
      host: ${HOST}
      port: ${PORT}
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 4380000000

mybatis:
  type-aliases-package: com.example.let.server.domain
  configuration:
    map-underscore-to-camel-case: true
    default-executor-type: BATCH
    default-fetch-size: 100
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.example.let.server.domain.mealmenu.service.impl.MealMenuServiceImpl: INFO
    org.springframework.jdbc.core: WARN
    org.springframework.transaction: WARN