name: Deploy to EC2

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 프로젝트 디렉토리로 이동
          cd /home/ubuntu/LET_SERVER
          
          # 최신 코드 풀
          git pull origin main
          
          # Docker 이미지 빌드
          docker build -t let-server .
          
          # 기존 컨테이너 중지 및 삭제
          docker stop let-server || true
          docker rm let-server || true
          
          # 새 컨테이너 실행
          docker run -d \
            --name let-server \
            --restart unless-stopped \
            -p 8080:8080 \
            -e DB_URL="${{ secrets.DB_URL }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e PASSWORD="${{ secrets.DB_PASSWORD }}" \
            -e HOST="${{ secrets.REDIS_HOST }}" \
            -e PORT="${{ secrets.REDIS_PORT }}" \
            -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
            let-server
          
          # 배포 확인
          docker ps | grep let-server
          echo "Deployment completed!" 